version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    groups:
      patch-updates:
        patterns:
          - "*"
        exclude-patterns:
          - "google.golang.org/api"
          - "google.golang.org/genproto*"
          - "google.golang.org/grpc"
          - "google.golang.org/protobuf"
          - "modernc.org/*"
        update-types:
          - "patch"
    open-pull-requests-limit: 5
    reviewers:
      - "dl-alexandre"
    assignees:
      - "dl-alexandre"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:15"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "dl-alexandre"
    assignees:
      - "dl-alexandre"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
